version: 2
jobs:
  build:
    working_directory: ~/tmp
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - restore-cache:
          keys:
            - v1-dependencies-{{ checksum "backend/package.json" }}
            - vi-dependencies-
      - run:
          name: Installing modules
          command: cd backend/ && npm ci
      - save-cache:
          paths:
            - ./backend/node_modules
          key: v1-dependencies-{{  checksum "backend/package.json" }}
      - run:
          name: Building backend code
          command: cd backend/ && npm run build

  deploy:
    working_directory: ~/tmp
    docker:
      - image: hashicorp/terraform
    steps:
      - checkout
      - run:
          name: Listing environment variables
          command: printenv
      - run:
          name: Extracting environment variables
          command: printenv >> infrastructure/terraform.tfvars
      - run:
          name: Initialising terraform
          command: cd infrastructure/ && terraform init -reconfigure -force-copy -backend=true -backend-config "bucket=geet-tf-state-bucket" -backend-config "key=terraform.tfstate" -backend-config "region=us-west-2"

workflows:
  version: 2
  jobs:
    - build
    - deploy