version: 2
jobs:
  build:
    working_directory: ~/tmp
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - run: cd backend/ && npm ci
      - run: cd backend/ && npm run build