version: 2
jobs:
  build:
    working_directory: ~/tmp
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - restore-cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - vi-dependencies-
      - run: cd backend/ && npm ci
      - save-cache:
          paths:
            - ./backend/node_modules
          key: v1-dependencies-{{  checksum "package.json" }}
      - run: cd backend/ && npm run build